//AUTHENTICATION ACTION
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";


//ACTIVITIES ACTION
export const SET_ACTIVITIES = "SET_ACTIVITIES"
export const SAVED_ACTIVITIES = "SAVED_ACTIVITIES"

export const SELECTED_ACTIVITIES = "SELECTED_ACTIVITIES"



//HOTEL ACTION
export const GET_HOTELS = "GET_HOTELS"
export const SAVE_HOTEL = "SAVE_HOTEL"
export const SELECTED_HOTEL = "SELECTED_HOTEL"

//FLIGHT ACTION
export const POST_FLIGHT = "POST_FLIGHT"

