//AUTHENTICATION ACTION
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";


//ACTIVITIES ACTION
export const SET_ACTIVITIES = "SET_ACTIVITIES"